### ISSUE TITLE
Add your metadata file to the _config

### ISSUE THREAD

**Issue by jesseajohnston** [srosb1491/cb-csv#1]
### Current Behavior

If the sample contents you've added are not displaying, you may need to add your metadata csv top the `_config.yml` file in the main repo. That's where the jekyll generator will look to see what metadata and digital objects to display.

**Comment by srosb1491** [comment]
So, I updated the _config.yml file  and the content I had for Lab 5 shows up. However, it is only the new data and the sample data (original data) no longer appears. I think only one metadata file can be used?  So for Lab 5, maybe I was supped to just add the new items to the exisiting metadata sheet?

**Comment by jesseajohnston** [comment]
Yes, the goal is just to have the new, added items for now. -JJ
